name: Build and Push Docker Images

on:
  push:
    branches: [ prod ]
  pull_request:
    branches: [ prod ]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set image name to lowercase
        run: echo "IMAGE_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push CLI image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.cli
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-cli:latest

      - name: Build and push NGINX image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.nginx
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-nginx:latest
          build-args: |
            CLI_IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-cli:latest

      - name: Build and push PHP-FPM image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.php
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-fpm:latest
          build-args: |
            CLI_IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-cli:latest
